name = "flotiq-blog"
main = "worker-index.js"
compatibility_date = "2024-12-05"

[site]
bucket = "./public"

[env.production]
name = "flotiq-blog-production"
routes = [
    { pattern = "flotiq.com/blog", zone_name = "flotiq.com", custom_domain = false},
    { pattern = "flotiq.com/blog/*", zone_name = "flotiq.com", custom_domain = false}
]