name = "flotiq-blog"
main = "worker-index.js"
compatibility_date = "2024-01-09"

[site]
bucket = "./public"

[env.production]
name = "flotiq-blog-production"

[env.staging]
name = "flotiq-blog-staging"
route = { pattern = "flotiq.com/staging-blog", zone_name = "flotiq.com", custom_domain = true }
